name = "seno-game"
compatibility_date = "2026-05-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "SENO_DB"
database_name = "seno-counter"
database_id = "5a1e8da2-c164-4dcc-a1c6-d590a9ccf717"
